Improve compatibility for MW1.35+
nbdd0121/MW-FlowThread pull request #57
Opened 2020-10-08 15:58 UTC by StarHeartHunt

Fix 'User Comments' link in the sidebar & 'Comment Control' action

2020-10-08 17:18 UTC, nbdd0121 requested changes
Thanks for the PR. Could you address the two comments please?

2020-10-08 17:18 UTC, nbdd0121 commented on includes/Hooks.php
> +		}
This comparison seems to be unnecessary.

2020-10-08 17:18 UTC, nbdd0121 commented on includes/Hooks.php
> +
Is there a reason not to remove onSkinTemplateOutputPageBeforeExec all together?

2020-10-09 04:44 UTC, StarHeartHunt reviewed
That's my fault.
I have removed onSkinTemplateOutputPageBeforeExec from the code in the latest commit.

2020-10-09 04:58 UTC, StarHeartHunt reviewed
Removed redundant code.

2020-10-09 18:27 UTC, nbdd0121 commented
Squashed and merged

2020-10-09 18:27 UTC, closed without merging